# -*- coding: utf-8 -*-
"""Class_Assignment_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nszLydpc2X-nM4C-MVX-ZB_oWGIIuOn
"""

! pip install streamlit

import streamlit as st
import pandas as pd

# Title of the app
st.title('Class Assignment 5')

# Ask for the user's name
name = st.text_input("Enter your name:")

# Greet the user if a name is provided
st.write(f"Hi {name}, nice to have you here!")