# -*- coding: utf-8 -*-
"""project_try2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RT3ePyhERXRieu12iabaNx2Zgihj31kQ
"""

# -*- coding: utf-8 -*-
"""streamlit_app.py

Interactive Gun Violence Data Visualization App
"""

import pandas as pd
import streamlit as st

# Preload Data
def read_large_csv(url):
    try:
        chunk_size = 1000
        chunks = pd.read_csv(url, encoding="ISO-8859-1", sep=",", on_bad_lines="skip", chunksize=chunk_size)
        df_list = [chunk for chunk in chunks]
        df = pd.concat(df_list, ignore_index=True)
        return df.dropna()
    except Exception as e:
        print(f"Error loading data: {e}")
        return None

file_url = "https://raw.githubusercontent.com/BlassMolina03/ENG-220-MATLAB-PROJECTS/main/Data%20Sheet%201.csv"
df = read_large_csv(file_url)

if df is not None:
    st.write("Data Loaded Successfully.")

    # Clean Data
    df['Incident Date'] = pd.to_datetime(df['Incident Date'], errors='coerce')
    df = df.dropna(subset=['Incident Date'])
    df['day_of_week'] = df['Incident Date'].dt.day_name()

    # Process Data for Monthly Analysis
    df['month_year'] = df['Incident Date'].dt.to_period('M')
    monthly_counts = df['month_year'].value_counts().sort_index()

    # Display Monthly Increase Chart
    st.subheader("Monthly Gun Violence Incidents")
    st.line_chart(monthly_counts)

    # Process Data for Gender Analysis
    gender_counts = df['Participant Gender'].value_counts()

    # Display Gender Chart
    st.subheader("Incidents by Gender")
    st.bar_chart(gender_counts)

else:
    st.write("Failed to load data.")