# -*- coding: utf-8 -*-
"""project_try1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RT3ePyhERXRieu12iabaNx2Zgihj31kQ
"""

# -*- coding: utf-8 -*-
"""streamlit_app.py

Interactive Gun Violence Data Visualization App
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Preload Data
def read_large_csv(url):
    try:
        chunk_size = 1000
        chunks = pd.read_csv(url, encoding="ISO-8859-1", sep=",", on_bad_lines="skip", chunksize=chunk_size)
        df_list = [chunk for chunk in chunks]
        df = pd.concat(df_list, ignore_index=True)
        return df.dropna()
    except Exception as e:
        print(f"Error loading data: {e}")
        return None

file_url = "https://raw.githubusercontent.com/BlassMolina03/ENG-220-MATLAB-PROJECTS/main/Data%20Sheet%201.csv"
df = read_large_csv(file_url)

if df is not None:
    print("Data Loaded Successfully.")
    # Clean Data
    df['Incident Date'] = pd.to_datetime(df['Incident Date'], errors='coerce')
    df = df.dropna(subset=['Incident Date'])
    df['day_of_week'] = df['Incident Date'].dt.day_name()

    # Process Data for Monthly Analysis
    df['month_year'] = df['Incident Date'].dt.to_period('M')
    monthly_counts = df['month_year'].value_counts().sort_index()

    # Plot Data: Monthly Increase
    fig1, ax1 = plt.subplots(figsize=(10, 6))
    monthly_counts.plot(kind='line', ax=ax1, marker='o')
    ax1.set_title("Monthly Gun Violence Incidents")
    ax1.set_xlabel("Month-Year")
    ax1.set_ylabel("Number of Incidents")
    plt.xticks(rotation=45)
    plt.tight_layout()
    fig1.savefig("monthly_trend.png")
    print("Monthly Increase Chart Saved.")

    # Process Data for Gender Analysis
    gender_counts = df['Participant Gender'].value_counts()

    # Plot Data: Per Gender
    fig2, ax2 = plt.subplots(figsize=(8, 5))
    sns.barplot(x=gender_counts.index, y=gender_counts.values, ax=ax2, palette="viridis")
    ax2.set_title("Incidents by Gender")
    ax2.set_xlabel("Gender")
    ax2.set_ylabel("Number of Incidents")
    plt.tight_layout()
    fig2.savefig("gender_analysis.png")
    print("Gender Chart Saved.")
else:
    print("Failed to load data.")